version: '3.1'
services:
  dev-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dump/db.sql:/docker-entrypoint-initdb.d/init.sql

  test-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_service_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./dump/db.sql:/docker-entrypoint-initdb.d/init.sql
